name: Build Deauther V3 Nightly

on: [repository_dispatch]

jobs:

  build-bin:
    name: "Build .bin file"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Clone esp8266_deauther
        uses: actions/checkout@v2
        with:
          repository: 'SpacehuhnTech/esp8266_deauther'
          ref: 'v3'

      - name: Install Arduino CLI
        run: |
            mkdir ~/bin
            curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/bin sh
      
      - name: Download Board Indices
        run: ~/bin/arduino-cli core update-index
        
      - name: Install Deauther Board
        run: ~/bin/arduino-cli core install deauther:esp8266
        
      - name: Compile
        run: ~/bin/arduino-cli compile esp8266_deauther --fqbn deauther:esp8266:d1_mini --output-dir build
      
      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: YYYY_MM_DD
#          utcOffset: "+08:00"

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v1-release
        env:
          TIME: "${{ steps.current-time.outputs.formattedTime }}"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/esp8266_deauther.ino.bin
          asset_name: esp8266_deauther_V3_1M_Nightly.bin
          tag: nightly
          overwrite: true
